name: Build Wheels

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        # Configure cibuildwheel to build native archs ('auto'), and some
        # emulated ones
        CIBW_ARCHS_LINUX: auto aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_ARCHS_WINDOWS: auto
        
        # Use manylinux for maximum Linux compatibility
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
        
        # Skip some builds
        CIBW_SKIP: cp36-* cp37-* pp* *-musllinux*
        
        # Install dependencies for each platform
        CIBW_BEFORE_ALL_LINUX: >
          yum install -y cmake3 ninja-build gcc-c++ make git &&
          ln -sf /usr/bin/cmake3 /usr/bin/cmake &&
          git --version
        
        CIBW_BEFORE_ALL_MACOS: >
          brew install cmake ninja
        
        CIBW_BEFORE_ALL_WINDOWS: >
          choco install cmake ninja
        
        # Install Python dependencies
        CIBW_BEFORE_BUILD: >
          pip install --upgrade pip setuptools wheel &&
          pip install numpy pybind11[global] cmake ninja &&
          pip install pydicom>=2.3.0 zstandard>=0.18.0
        
        # Test core functionality only (avoid complex dependencies)
        CIBW_TEST_REQUIRES: >
          numpy
        CIBW_TEST_COMMAND: >
          python -c "from dicube.codecs.jph import JphCodec; 
          import numpy as np;
          codec = JphCodec(); 
          assert codec.is_available(), 'JphCodec not available';
          img = np.ones((32, 32), dtype=np.uint8);
          encoded = codec.encode(img);
          decoded = codec.decode(encoded);
          assert decoded.shape == img.shape, 'Decode shape mismatch';
          print('✓ Wheel test passed')"
        
        # Environment variables
        CIBW_ENVIRONMENT_LINUX: >
          OPENJPH_BUILD_STATIC=ON
          CMAKE_BUILD_TYPE=Release
          CMAKE_BUILD_PARALLEL_LEVEL=2
        
        CIBW_ENVIRONMENT_MACOS: >
          OPENJPH_BUILD_STATIC=ON
          CMAKE_BUILD_TYPE=Release
          CMAKE_BUILD_PARALLEL_LEVEL=2
          MACOSX_DEPLOYMENT_TARGET=10.14
        
        CIBW_ENVIRONMENT_WINDOWS: >
          OPENJPH_BUILD_STATIC=ON
          CMAKE_BUILD_TYPE=Release
          CMAKE_BUILD_PARALLEL_LEVEL=2

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

 