name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.12']  # 只测试最低和最高版本
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      # 确保子模块被正确初始化
      - name: Ensure submodules are initialized
        run: |
          git submodule update --init --recursive
          if [ ! -f "openjph/CMakeLists.txt" ]; then
            echo "Error: OpenJPH submodule not properly initialized"
            exit 1
          fi
          echo "OpenJPH submodule initialized successfully"
      
      - uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
          install-dev: 'true'
      
      # 安装和测试
      - name: Install package
        run: |
          pip install -e .[dev]
      
      - name: Run tests
        run: |
          pytest tests/ -v --tb=short
          
          # 基本导入测试
          python -c "
          import dicube
          from dicube.codecs.jph import JPHCodec
          print(f'✅ dicube version: {dicube.__version__}')
          " 